insert into employees (first_work_day, email, first_name, first_day_of_introductory_training, job_position, last_name, last_day_of_introductory_training, nr_of_department) values ('2020-01-01', 'karma0510@gmail.com','Karolina', '2020-01-01', 'Data Analyst', 'Maciejewska', '2020-01-02', 9);
insert into employees (first_work_day, email, first_name, first_day_of_introductory_training, job_position, last_name, last_day_of_introductory_training, nr_of_department) values ('2021-11-10', 'abc@gmail.com','Michal', '2021-11-10', 'Java Developer', 'Sokolowski', '2021-11-11', 9);
insert into employees (first_work_day, email, first_name, first_day_of_introductory_training, job_position, last_name, last_day_of_introductory_training, nr_of_department) values ('2022-05-31', 'def@gmail.com','Mateusz', '2022-05-31', 'C++ Developer', 'Maciejewski', '2022-06-01', 3);

insert into register_of_accidents (accident_id, date_of_accidents, is_recognized_as_accident, number_of_victims, place_of_accident, number_of_accidental_protocole, type_of_accidents, responsible_branch) values (12022, "2022-02-03", 1, 1, "Lodz, ul. Zgierska 4 m. 15", 1, 0, 9);
insert into register_of_accidents (accident_id, date_of_accidents, is_recognized_as_accident, number_of_victims, place_of_accident, number_of_accidental_protocole, type_of_accidents, responsible_branch) values (22022, "2022-03-04", 1, 2, "Pabianice, ul. 3 Maja 4", 2, 3, 9);
insert into register_of_accidents (accident_id, date_of_accidents, is_recognized_as_accident, number_of_victims, place_of_accident, number_of_accidental_protocole, type_of_accidents, responsible_branch) values (32022, "2022-04-05", 1, 1, "Pabianice, ul. 3 Maja 4", 3, 2, 3);

insert into job_position (is_biological_risk, is_chemical_risk, is_mental_stress, is_physical_risk, job_position_name) values(0, 0, 0, 1, "C++ Developer");
insert into job_position (is_biological_risk, is_chemical_risk, is_mental_stress, is_physical_risk, job_position_name) values(0, 0, 0, 1, "Java Developer");
insert into job_position (is_biological_risk, is_chemical_risk, is_mental_stress, is_physical_risk, job_position_name) values(0, 0, 0, 1, "Data Analyst");

insert into periodic_training_register(employee_id, training_start_date, periodic_training_date, periodic_training_exam_date) values (1, '2020-01-01', '2021-01-01', '2021-01-05');
insert into periodic_training_register(employee_id, training_start_date, periodic_training_date, periodic_training_exam_date) values (2, '2021-11-10', '2021-11-10', '2021-11-15');
insert into periodic_training_register(employee_id, training_start_date, periodic_training_date, periodic_training_exam_date) values (3, '2022-05-31', null, null);

insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date, nr_of_department) values (1, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null, '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (1, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3, '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (1, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 9);

insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date,nr_of_department) values (2, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null,  '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (2, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3,  '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (2, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date,nr_of_department) values (3, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null,  '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (3, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3,  '2022-01-01', 9);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (3, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 9);

insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date,nr_of_department) values (1, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (1, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (1, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date,nr_of_department) values (2, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (2, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (2, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions , last_update_date,nr_of_department) values (3, "oparzenie", "noszenie gorącej herbaty", 3, 3, 3, null, null, null, null,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions ,last_update_date, nr_of_department) values (3, "porazenie pradem", "uszkodzenie kabla, napięcie wystepujace na komputerze", 3, 2, 4, "Sprawdzanie sprzetu przed rozpoczeciem pracy",1, 3, 3,  '2022-01-01', 3);
insert into mydatabase2.risk (job_position_job_position_id, dangerous, cause_of_dangerous, probability, rank_of_effects, risk, preventive_actions, probability_after_preventive_actions, rank_of_effects_after_preventive_actions, risk_after_preventive_actions,last_update_date, nr_of_department) values (3, "potknięcie się", "wystające części na poziomie podłogi", 2, 2, 3, null, null, null, null,  '2022-01-01', 3);
